export const INITIAL_QUOTES = [
  "Turn life's friction into focused productivity.",
  "Your time is your most valuable currency. Spend it on growth, not gaps.",
  "Waiting is not a pause in life; it is an opportunity for a pivot.",
  "Don't just kill time; give it a purpose.",
  "Focus is the art of knowing what to ignore, especially while waiting.",
  "The secret to productivity is managing your energy, not just your time.",
  "Every small gap in your day is a blank canvas for curiosity.",
  "Productivity is being able to do things that you were never able to do before.",
  "Reclaim your focus, and you reclaim your future.",
  "Friction is just an invitation to find a better flow.",
  "The time you spend waiting is the time you spend becoming.",
  "Your attention is the most valuable thing you own. Guard it fiercely.",
  "Waiting rooms are the gymnasiums of the mind.",
  "Don't let a queue become a void. Fill it with a spark of learning.",
  "The gap between what you are and what you want to be is filled with how you spend your spare minutes.",
  "Focus is the new IQ. Train it in the moments others ignore.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "The best way to spend time is to invest it in yourself.",
  "Waiting is a period of grace to refine your focus.",
  "Transform every delay into a discovery.",
  "Your brain is a high-performance machine. Don't let it idle in the commute.",
  "The strongest minds are those that find utility in the useless moments.",
  "Stop waiting for the 'right time.' Use the 'waiting time.'",
  "Productivity is never an accident. It is always the result of a commitment to excellence.",
  "Focus on being productive instead of busy.",
  "A reclaimed minute is a won battle against doomscrolling.",
  "Your focus determines your reality.",
  "Waiting is a gift of time you didn't know you had.",
  "The time you save today is the freedom you enjoy tomorrow.",
  "Be intentional with your gaps, and your goals will follow.",
  "Stop waiting for the world to move. Move the world in your waiting.",
  "Turn the friction of a commute into the momentum of a mission.",
  "Curiosity is the antidote to the boredom of waiting.",
  "Deep work starts with reclaiming shallow moments.",
  "The world belongs to those who use their 'in-betweens' wisely.",
  "Small habits of focus build mountains of success.",
  "Don't wait for inspiration. Use the wait for preparation.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Your future self will thank you for the minutes you reclaimed today.",
  "Turn 'I have to wait' into 'I get to learn.'",
  "The best investment is in the tools of your own mind.",
  "Focus is the key that unlocks the door to productivity.",
  "Waiting is a test of intention. What will you do with it?",
  "Productivity is the deliberate use of time.",
  "Make your waiting count, so you don't have to count the wait.",
  "A mind at rest stays at rest; a mind in WaitLess stays ahead.",
  "Friction exists to be overcome by focus.",
  "The moments in between are where the magic happens.",
  "Reclaim the scroll. Embrace the soul.",
  "Your time is limited. Don't waste it waiting for nothing."
];
