export const WORD_LIST = [
  "APPLE", "BEACH", "BRAIN", "BREAD", "BRUSH", "CHAIR", "CHEST", "CHORD",
  "CLICK", "CLOCK", "CLOUD", "DANCE", "DIARY", "DRINK", "DRIVE", "EARTH",
  "FEAST", "FIELD", "FLAME", "FLOUR", "FRUIT", "GLASS", "GRAPE", "GREEN",
  "GRIND", "GUIDE", "HEART", "HOUSE", "JUICE", "LIGHT", "LEMON", "MUSIC",
  "NIGHT", "OCEAN", "PAINT", "PAPER", "PHONE", "PIANO", "PILOT", "PLANE",
  "PLANT", "PLATE", "PRIDE", "QUEEN", "QUIET", "RADIO", "RAISE", "RANGE",
  "REACH", "RELAX", "RIVER", "ROBOT", "ROCKY", "ROUND", "SCENE", "SHARP",
  "SHELF", "SHIRT", "SKILL", "SLEEP", "SMILE", "SNAKE", "SPACE", "SPOON",
  "STAIR", "START", "STEAM", "STEEL", "STONE", "STORE", "STORM", "STORY",
  "STUDY", "TABLE", "TASTE", "TIGER", "TOUCH", "TRAIN", "TRUCK", "VOICE",
  "WATER", "WATCH", "WHALE", "WORLD", "WRITE", "YOUTH", "ZEBRA"
];
