import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DevBar } from "@/components/debug/DevBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WaitLess",
  description: "Generated by create next app",
};


import { AuthProvider } from "@/components/auth/AuthProvider";
import { NotificationInitializer } from "@/components/NotificationInitializer";
import { ToastContainer } from "@/components/ui/ToastNotification";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <ToastContainer />
          <NotificationInitializer />
          {children}
        </AuthProvider>
        <DevBar />
      </body>
    </html>
  );
}
