

export const concepts = [
    {
        "concept_name": "Solipsism",
        "concept_text": "Solipsism is the radical philosophical position asserting that only one's own mind is guaranteed to exist. From this viewpoint, knowledge of anything outside the self—such as the external physical world or the conscious experiences of other individuals—is fundamentally impossible to verify. It implies that the universe and everyone in it might merely be complex projections, illusions, or fabrications generated by one's own isolated consciousness. This extreme form of skepticism challenges our most basic assumptions about reality, pushing us to question how we can truly know anything beyond our own immediate internal experiences.",
        "question 1": {
            "type": "mcq",
            "question_body": "What is the core claim of solipsism?",
            "options": [
                { "optiontext": "The mind and body are distinct substances.", "is_correct": false },
                { "optiontext": "Only one's own mind is certain to exist.", "is_correct": true },
                { "optiontext": "Knowledge is derived primarily from sensory experience.", "is_correct": false },
                { "optiontext": "The universe is composed of many independent minds.", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "In a solipsistic framework, other people are regarded as:",
            "options": [
                { "optiontext": "Moral agents with equal rights.", "is_correct": false },
                { "optiontext": "Divine entities guiding the self.", "is_correct": false },
                { "optiontext": "Potentially non-existent or mental constructs.", "is_correct": true },
                { "optiontext": "The primary source of objective truth.", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "If you could never prove that other people have consciousness, how would that change the way you treat them?"
        }
    },
    {
        "concept_name": "Eternal Recurrence",
        "concept_text": "Popularized by the philosopher Friedrich Nietzsche, eternal recurrence is the thought experiment suggesting that the universe and all events within it have already occurred and will continue to recur infinitely. In this concept, there is no final state of the universe; instead, you will live your exact same life, with all its joys and sufferings, over and over again for eternity, without any changes. Nietzsche used this idea not necessarily as a literal physical truth, but as a psychological test to measure one's ultimate affirmation and love of life.",
        "question 1": {
            "type": "mcq",
            "question_body": "Which philosopher is most famously associated with the concept of Eternal Recurrence?",
            "options": [
                { "optiontext": "Immanuel Kant", "is_correct": false },
                { "optiontext": "Friedrich Nietzsche", "is_correct": true },
                { "optiontext": "John Stuart Mill", "is_correct": false },
                { "optiontext": "Socrates", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "Eternal Recurrence serves primarily as a thought experiment for:",
            "options": [
                { "optiontext": "Mathematical probability.", "is_correct": false },
                { "optiontext": "Affirming one's life and choices.", "is_correct": true },
                { "optiontext": "Proving the existence of a deity.", "is_correct": false },
                { "optiontext": "Calculating the age of the universe.", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "If you were told you had to live your current life over and over for eternity, what is one thing you would change immediately?"
        }
    },
    {
        "concept_name": "The Categorical Imperative",
        "concept_text": "The categorical imperative is the central philosophical concept in the deontological moral philosophy of Immanuel Kant. It serves as an absolute, unconditional requirement that must be obeyed in all circumstances and is justified as an end in itself. Its most famous formulation states that you should act only according to a maxim that you can simultaneously will to become a universal law of nature. Essentially, it demands that we must not make special exceptions for ourselves; an action is only morally right if it would be acceptable for everyone else to do the same thing.",
        "question 1": {
            "type": "mcq",
            "question_body": "The Categorical Imperative is a central element of which ethical system?",
            "options": [
                { "optiontext": "Deontology", "is_correct": true },
                { "optiontext": "Utilitarianism", "is_correct": false },
                { "optiontext": "Hedonism", "is_correct": false },
                { "optiontext": "Nihilism", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "According to the 'Universal Law' formulation, an action is immoral if:",
            "options": [
                { "optiontext": "It results in more pain than pleasure.", "is_correct": false },
                { "optiontext": "It violates a local law.", "is_correct": false },
                { "optiontext": "It cannot be consistently willed as a universal rule for everyone.", "is_correct": true },
                { "optiontext": "The person performing it feels guilty.", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "Think of a common white lie. What would happen to society if 'always telling white lies' became a universal law?"
        }
    },
    {
        "concept_name": "Absurdism",
        "concept_text": "Absurdism is a philosophical perspective highlighting the fundamental conflict between the human tendency to search for inherent value, meaning, and order in life, and the silent, cold, and meaningless nature of the universe. Associated closely with Albert Camus, it posits that our efforts to find objective meaning will ultimately fail because no such meaning exists. However, rather than succumbing to despair or seeking false hope in religion, the absurdist embraces this reality. We are encouraged to accept the absurd nature of existence and live defiantly, finding personal freedom in the rebellion against meaninglessness.",
        "question 1": {
            "type": "mcq",
            "question_body": "According to Albert Camus, how should one respond to the 'Absurd'?",
            "options": [
                { "optiontext": "By ending one's life.", "is_correct": false },
                { "optiontext": "By creating a religion to hide the truth.", "is_correct": false },
                { "optiontext": "By embracing the struggle and living defiantly.", "is_correct": true },
                { "optiontext": "By ignoring the lack of meaning entirely.", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "Absurdism is most closely related to which other movement?",
            "options": [
                { "optiontext": "Rationalism", "is_correct": false },
                { "optiontext": "Existentialism", "is_correct": true },
                { "optiontext": "Stoicism", "is_correct": false },
                { "optiontext": "Empiricism", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "Does the lack of an objective meaning in the universe make your personal goals more or less important to you? Why?"
        }
    },
    {
        "concept_name": "Panpsychism",
        "concept_text": "Panpsychism is the philosophical theory proposing that mind, consciousness, or a fundamental mind-like quality is a universal and primordial feature of all things in reality. Rather than viewing consciousness as an emergent property that only arises in complex biological brains, panpsychism suggests that even the smallest building blocks of matter, such as electrons and quarks, possess a basic form of proto-consciousness. This theory aims to solve the notoriously difficult problem of how subjective experience can emerge from entirely non-conscious physical matter by asserting that experience was simply there from the very beginning.",
        "question 1": {
            "type": "mcq",
            "question_body": "What does Panpsychism claim about consciousness?",
            "options": [
                { "optiontext": "It only exists in biological brains.", "is_correct": false },
                { "optiontext": "It is an illusion created by physics.", "is_correct": false },
                { "optiontext": "It is fundamental to all matter in the universe.", "is_correct": true },
                { "optiontext": "It can only be achieved through meditation.", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "Panpsychism attempts to solve which famous philosophical dilemma?",
            "options": [
                { "optiontext": "The Trolley Problem", "is_correct": false },
                { "optiontext": "The Hard Problem of Consciousness", "is_correct": true },
                { "optiontext": "The Problem of Evil", "is_correct": false },
                { "optiontext": "The Ship of Theseus", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "If an electron has a tiny 'flicker' of consciousness, does that change your moral responsibility toward the physical world?"
        }
    },
    {
        "concept_name": "Utilitarianism",
        "concept_text": "Utilitarianism is a prominent consequentialist ethical theory determining right from wrong by focusing on the outcomes of our actions. It is driven by the principle of utility, which argues that the most morally correct action is the one that produces the greatest overall happiness or pleasure while minimizing pain and suffering for the greatest number of sentient beings. Championed by philosophers like Jeremy Bentham and John Stuart Mill, it requires an impartial calculation of consequences, meaning your own happiness counts no more and no less than the happiness of any other individual affected by your choices.",
        "question 1": {
            "type": "mcq",
            "question_body": "What is the 'Greatest Happiness Principle'?",
            "options": [
                { "optiontext": "The idea that one should always pursue personal wealth.", "is_correct": false },
                { "optiontext": "Actions are right if they promote the greatest happiness for the greatest number.", "is_correct": true },
                { "optiontext": "Happiness is a reward for following religious laws.", "is_correct": false },
                { "optiontext": "Only the elite deserve to be happy.", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "Utilitarianism judges an action based on its:",
            "options": [
                { "optiontext": "Intentions", "is_correct": false },
                { "optiontext": "Consequences", "is_correct": true },
                { "optiontext": "Legality", "is_correct": false },
                { "optiontext": "Traditional value", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "Is it ever okay to harm one innocent person to save a hundred lives? Explain your reasoning."
        }
    },
    {
        "concept_name": "Epistemological Nihilism",
        "concept_text": "Epistemological nihilism is a radical and extreme form of philosophical skepticism that fundamentally denies the possibility of human knowledge. It argues that there is no objective truth, or at the very least, that human beings lack any reliable method or cognitive capacity to access, comprehend, or verify it. From this perspective, all beliefs, scientific theories, and sensory experiences are equally invalid or unjustifiable. By dismantling the foundations of how we claim to know things, epistemological nihilism suggests that all human claims to certainty are ultimately baseless illusions.",
        "question 1": {
            "type": "mcq",
            "question_body": "Epistemological Nihilism is primarily concerned with:",
            "options": [
                { "optiontext": "The existence of God.", "is_correct": false },
                { "optiontext": "The possibility of certain knowledge.", "is_correct": true },
                { "optiontext": "The distribution of wealth.", "is_correct": false },
                { "optiontext": "The beauty of art.", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "A nihilist in epistemology might argue that all 'facts' are actually:",
            "options": [
                { "optiontext": "Scientifically proven constants.", "is_correct": false },
                { "optiontext": "Divine revelations.", "is_correct": false },
                { "optiontext": "Unjustified beliefs or social constructs.", "is_correct": true },
                { "optiontext": "Obvious to anyone with common sense.", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "If we can never truly 'know' anything for certain, what should be the basis for our laws and decisions?"
        }
    },
    {
        "concept_name": "Phenomenology",
        "concept_text": "Phenomenology is a philosophical movement focused on the systematic study of conscious experience and structures of consciousness as experienced from the first-person perspective. Founded by Edmund Husserl, it intentionally sets aside questions about the objective, independent reality of the external world. Instead, it directs intense focus toward how things appear directly to us—the \"phenomena.\" By closely examining our perceptions, thoughts, memories, and emotions without pre-existing biases or scientific assumptions, phenomenology seeks to understand the essential features of human consciousness and how we actively interpret and make sense of our lived realities.",
        "question 1": {
            "type": "mcq",
            "question_body": "What is the primary focus of Phenomenology?",
            "options": [
                { "optiontext": "Subatomic particles.", "is_correct": false },
                { "optiontext": "Linguistic structures.", "is_correct": false },
                { "optiontext": "Subjective experience and 'the things themselves'.", "is_correct": true },
                { "optiontext": "Historical economic cycles.", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "Which philosopher founded formal Phenomenology?",
            "options": [
                { "optiontext": "Edmund Husserl", "is_correct": true },
                { "optiontext": "Thomas Hobbes", "is_correct": false },
                { "optiontext": "David Hume", "is_correct": false },
                { "optiontext": "Karl Marx", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "Describe the experience of 'time' when you are bored versus when you are having fun. How does this illustrate phenomenological study?"
        }
    },
    {
        "concept_name": "Determinism",
        "concept_text": "Determinism is the philosophical proposition that every single event, including every human decision and action, is the inevitable and unavoidable result of preceding events and the laws of nature. It envisions the universe as a complex chain of cause and effect stretching back to the beginning of time. Under strict causal determinism, if a highly advanced intellect knew the exact precise state of every particle in the universe at one moment, it could perfectly predict the entire future. This concept poses a significant challenge to the traditional idea of human free will and moral responsibility.",
        "question 1": {
            "type": "mcq",
            "question_body": "If Determinism is true, what is logically threatened?",
            "options": [
                { "optiontext": "Gravity", "is_correct": false },
                { "optiontext": "Free will", "is_correct": true },
                { "optiontext": "Mathematics", "is_correct": false },
                { "optiontext": "Evolution", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "Causal determinism suggests that if we knew the state of every atom at the start of the universe, we could:",
            "options": [
                { "optiontext": "Predict all future events perfectly.", "is_correct": true },
                { "optiontext": "Change the past.", "is_correct": false },
                { "optiontext": "Find a way to live forever.", "is_correct": false },
                { "optiontext": "Prove that logic is false.", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "If your life path was already decided by the Big Bang, do you think people should still be punished for crimes? Why or why not?"
        }
    },
    {
        "concept_name": "Virtue Ethics",
        "concept_text": "Virtue ethics is a major approach to moral philosophy that emphasizes the development of an individual's character and moral virtues, rather than focusing purely on following rules or calculating the consequences of actions. Tracing its roots back to Aristotle, this framework asks not \"What should I do?\" but rather \"What kind of person should I be?\" It suggests that practicing virtues like courage, honesty, and compassion leads to human flourishing. A morally right act is simply one that a virtuous person would characteristically do in those specific circumstances, striking a balance between extreme behaviors.",
        "question 1": {
            "type": "mcq",
            "question_body": "Which ancient philosopher is most closely linked to Virtue Ethics?",
            "options": [
                { "optiontext": "Aristotle", "is_correct": true },
                { "optiontext": "Rene Descartes", "is_correct": false },
                { "optiontext": "Arthur Schopenhauer", "is_correct": false },
                { "optiontext": "Jean-Paul Sartre", "is_correct": false }
            ]
        },
        "question 2": {
            "type": "mcq",
            "question_body": "What is the 'Golden Mean' in Virtue Ethics?",
            "options": [
                { "optiontext": "The average amount of money one should give to charity.", "is_correct": false },
                { "optiontext": "The desirable middle between two extremes, one of excess and one of deficiency.", "is_correct": true },
                { "optiontext": "A mathematical formula for happiness.", "is_correct": false },
                { "optiontext": "The rule that we should treat others as we want to be treated.", "is_correct": false }
            ]
        },
        "question 3": {
            "type": "text",
            "question_body": "Pick a virtue (e.g., Courage). What does the 'excess' and the 'deficiency' of that virtue look like in a real-life situation?"
        }
    }
]